### ISSUE TITLE
Is README incomplete?

### ISSUE THREAD

**Issue by ninest** [ReinBentdal/styled_widget#26]
I was thinking of using this in a new prject, but I realized that the README was incomplete:
- Core Concepts
  - Widget Tree
  - Implicit Animations
- More Examples

Is there an ETA for the documentation? Do you suggest I use Division instead?

**Comment by ReinBentdal** [comment]
Yes the documentation is incomplete. It hasnt been a priority yet however it is on the list of what should be done soon.
When it comes to using styled_widget or division i think it depends. Styled_widget is easy to understand without documentation. By placing a dot after a Widget, for example `Text().`, you will get a list of all methods available. Styled_widget is in a earlier development faze than division and will therefore most likely be more prone to breaking changes. So if you appreciate better documentation and something more stable, division might be the right choice.
The reason i started the styled_widget project is because i believed more in this approach than the division approach. So long term the plan is to focus more on styled_widget and getting it in a more stable and useful position.

**Comment by ninest** [comment]
Thank you for the detailed answer. I knew Division was great when I saw it, but styled_widgets is even better. I will be following its development

**Comment by ReinBentdal** [comment]
There is finally a new version out! The documentation is moved to the wiki page on github. It is quite lacking atm but i will try to improve it over time
