### ISSUE TITLE
Add support for stacked BoxShadows

### ISSUE THREAD

**Issue by esDotDev** [ReinBentdal/styled_widget#37]
Some drop-shadows designs require multiple shadows layered on top of eachother.

Currently each boxShadow will replace the one before it, would be nice if these stacked instead.

**Comment by ReinBentdal** [comment]
Using methods such as `backgroundColor` and `boxShadow` is great when you just want to access one particular box decoration property. As of version 0.2.0 chained box decoration methods will no longer merge into one box decoration. I stead it is recommended to use the `decorated` method when using more than one property. The same goes for multiple boxShadows. 
The reason is because of performance. There are less steps which is done in the background
